name: Daily Commit

on:
  schedule:
    # Runs daily at 05:30 UTC (adjust as needed)
    - cron: '30 5 * * *'
  workflow_dispatch:  # Allows manual triggering

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Commit with 21f3002603@ds.study.iitm.ac.in
        run: |
          # Configure git
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          
          # Create commit
          echo "Commit on $(date)" >> commit-log.txt
          git add commit-log.txt
          git commit -m "Daily automated commit"
          
          # Push changes
          git push origin HEAD
